apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: icwebapp-service
  name: icwebapp-service
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
  selector:
    app: icwebapp-deploy
  type: NodePort
status:
  loadBalancer: {}
