apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: odoo-service
  name: odoo-service
spec:
  ports:
  - name: 8069-8069
    port: 8069
    protocol: TCP
    targetPort: 8069
    nodePort: 30069
  selector:
    app: odoo-deployment
  type: NodePort
